export const events = [
  {
    id: 1,
    name: "Solarpunk Futurism Exhibition",
    slug: "solarpunk-futurism-exhibition",
    city: "Bristol",
    location: "Colston Hall",
    date: new Date("2025-06-15T19:00:00"),
    organizerName: "Eco-Art Collective",
    imageUrl: "https://images.unsplash.com/photo-1642178225043-f299072af862",
    description:
      "Explore visions of sustainable futures through immersive installations from 30 international artists. This exhibition merges ecological design with speculative fiction, showcasing how we might live in harmony with nature through renewable technologies and community-focused urban planning.",
  },
  {
    id: 2,
    name: "Queer Ecology Symposium",
    slug: "queer-ecology-symposium",
    city: "Barcelona",
    location: "Apollo",
    date: new Date("2025-07-22T10:00:00"),
    organizerName: "Rainbow Academia",
    imageUrl: "https://images.unsplash.com/photo-1541178735493-479c1a27ed24",
    description:
      "A day-long exploration of intersections between LGBTQ+ identities and environmental activism. Featuring keynote speakers from the fields of queer theory and ecological sciences, with workshops on sustainable queer communities and the politics of nature.",
  },
  {
    id: 3,
    name: "Green Wave Music Festival",
    slug: "green-wave-music-festival",
    city: "Barcelona",
    location: "Parc del Fòrum",
    date: new Date("2025-08-05T12:00:00"),
    organizerName: "EcoSound Collective",
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
    description:
      "Three days of electronic and indie music powered entirely by renewable energy. Featuring artists who incorporate environmental themes into their work, with sustainability workshops and a zero-waste policy. Come dance for the planet!",
  },
  {
    id: 4,
    name: "Post-Growth Economics Conference",
    slug: "post-growth-economics-conference",
    city: "London",
    location: "The Venue",
    date: new Date("2025-09-12T09:00:00"),
    organizerName: "New Economy Forum",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85",
    description:
      "Challenging the growth paradigm with alternative economic models that prioritize ecological balance and social equity. Speakers include leading degrowth economists, policymakers experimenting with wellbeing metrics, and community currency pioneers.",
  },
  {
    id: 5,
    name: "Trans Climate March",
    slug: "trans-climate-march",
    city: "London",
    location: "Parliament Square",
    date: new Date("2025-06-28T14:00:00"),
    organizerName: "Trans Ecologies Network",
    imageUrl: "https://images.unsplash.com/photo-1518893880334-a3c17c0cd228",
    description:
      "A vibrant march highlighting the disproportionate impact of climate change on trans communities worldwide, particularly in the Global South. Featuring performances, speeches, and a community fair with radical queer environmental groups.",
  },
  {
    id: 6,
    name: "Mycelium Connections: Fungi Art Show",
    slug: "mycelium-connections-fungi-art-show",
    city: "London",
    location: "Glyptoteket",
    date: new Date("2025-07-10T11:00:00"),
    organizerName: "LDN BioArt Network",
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd",
    description:
      "Artworks exploring fungal networks as metaphors for queer kinship and ecological interdependence. Includes living installations, spore prints, and a participatory mushroom cultivation workshop.",
  },
  {
    id: 7,
    name: "Decolonizing Politics",
    slug: "decolonizing-politics",
    city: "London",
    location: "Culture Club",
    date: new Date("2025-08-19T18:30:00"),
    organizerName: "Southern Ecologies",
    imageUrl: "https://images.unsplash.com/photo-1468071174046-657d9d351a40",
    description:
      "A series of dialogues addressing colonial legacies in environmental movements, featuring indigenous activists, scholars from former colonies, and representatives of climate justice organizations.",
  },
  {
    id: 8,
    name: "Biophilic Design Fair",
    slug: "biophilic-design-fair",
    city: "Stockholm",
    location: "Färgfabriken",
    date: new Date("2025-09-05T10:00:00"),
    organizerName: "Scandinavian Design Initiative",
    imageUrl: "https://images.unsplash.com/photo-1487958449943-2429e8be8625",
    description:
      "Showcasing architecture and products that reconnect humans with nature in urban environments. Includes living walls, modular green spaces, and community co-design sessions for public spaces.",
  },
  {
    id: 9,
    name: "Polyamory and Sustainability Panel",
    slug: "polyamory-and-sustainability-panel",
    city: "Glasgow",
    location: "Tramway",
    date: new Date("2025-07-30T16:00:00"),
    organizerName: "Ethical Non-Monogamy Collective",
    imageUrl: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70",
    description:
      "Exploring how alternative relationship structures can model resource sharing, reduced consumption, and community care. With sociologists, relationship coaches, and ecological footprint analysts.",
  },
  {
    id: 10,
    name: "Climate Anxiety Support Rave",
    slug: "climate-anxiety-support-rave",
    city: "Manchester",
    location: "The White Hotel",
    date: new Date("2025-08-12T22:00:00"),
    organizerName: "Therapeutic Activism",
    imageUrl: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3",
    description:
      "A night of cathartic dancing with climate psychologists offering support between DJ sets. Features spaces for emotional processing, group discussions, and resources for sustainable activism without burnout.",
  },
  {
    id: 11,
    name: "Radical Softness: Textile Art for Tough Times",
    slug: "radical-softness-textile-art",
    city: "Glasgow",
    location: "Tramway",
    date: new Date("2025-07-18T12:00:00"),
    organizerName: "Craftivist Network",
    imageUrl: "https://images.unsplash.com/photo-1563170351-be82bc888aa4",
    description:
      "Textile works exploring vulnerability as strength in climate crisis. Includes a communal knitting circle creating a 'Comfort Blanket for the Planet' from recycled materials.",
  },
  {
    id: 12,
    name: "Disability Justice and Climate Adaptation",
    slug: "disability-justice-climate-adaptation",
    city: "Brighton",
    location: "The Shedhouse",
    date: new Date("2025-09-22T14:00:00"),
    organizerName: "Accessible Futures",
    imageUrl: "https://images.unsplash.com/photo-1507101105822-7472b28e22ac",
    description:
      "Policy forum on ensuring climate resilience plans center disabled communities. With sign language interpretation, live captioning, and sensory-friendly breakout spaces.",
  },
  {
    id: 13,
    name: "Radical Ecology Gathering",
    slug: "radical-ecology-gathering",
    city: "Bristol",
    location: "The Cube Microplex",
    date: new Date("2025-05-15T10:00:00"),
    organizerName: "Bristol Climate Justice Collective",
    imageUrl: "https://images.unsplash.com/photo-1508784411316-02b8cd4d3a3a",
    description:
      "Exploring grassroots ecological resistance, rewilding, and anti-capitalist climate action. Workshops on land sovereignty, direct action, and eco-feminism.",
  },
  {
    id: 14,
    name: "Queer Liberation Festival",
    slug: "queer-liberation-festival",
    city: "Glasgow",
    location: "The Glad Café",
    date: new Date("2025-06-22T12:00:00"),
    organizerName: "Glasgow Queer Mutiny",
    imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622",
    description:
      "A radical celebration of queer resistance beyond Pride corporatism. Discussions on trans rights, sex worker solidarity, and queer anarchist struggles.",
  },
  {
    id: 15,
    name: "Decolonizing Scotland Symposium",
    slug: "decolonizing-scotland-symposium",
    city: "Edinburgh",
    location: "Out of the Blue Drill Hall",
    date: new Date("2025-07-08T09:30:00"),
    organizerName: "Decolonial Scotland Network",
    imageUrl: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1",
    description:
      "Unpacking Scotland’s colonial legacy and imagining reparative futures. Indigenous speakers, anti-racist educators, and land rematriation campaigns.",
  },
  {
    id: 16,
    name: "Socialist Bookfair",
    slug: "socialist-bookfair",
    city: "London",
    location: "Marx Memorial Library",
    date: new Date("2025-08-19T10:00:00"),
    organizerName: "Left Book Club",
    imageUrl: "https://images.unsplash.com/photo-1589998059171-988d887df646",
    description:
      "A day of revolutionary literature, from abolitionist theory to workers’ history. Publishers, zine makers, and radical authors in conversation.",
  },
  {
    id: 17,
    name: "Squatters & Housing Justice Assembly",
    slug: "squatters-housing-justice-assembly",
    city: "Barcelona",
    location: "Can Batlló",
    date: new Date("2025-09-05T17:00:00"),
    organizerName: "La Borda Cooperative",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    description:
      "Strategizing against gentrification and for community-controlled housing. Tenants’ unions, okupa collectives, and anti-eviction activists share tactics.",
  },
  {
    id: 18,
    name: "Indigenous Solidarity Teach-In",
    slug: "indigenous-solidarity-teach-in",
    city: "Bristol",
    location: "Kebel Social Centre",
    date: new Date("2025-10-12T14:00:00"),
    organizerName: "Bristol Indigenous Action",
    imageUrl: "https://images.unsplash.com/photo-1519817650390-64a93db51149",
    description:
      "Learning from global Indigenous struggles against extraction.",
  },
  {
    id: 19,
    name: "Anti-Fascist Film Festival",
    slug: "anti-fascist-film-festival",
    city: "Glasgow",
    location: "Govanhill Baths",
    date: new Date("2025-11-09T18:30:00"),
    organizerName: "Red Glasgow Cinema",
    imageUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c",
    description:
      "Screening documentaries on antifascist resistance, from Cable Street to today. Q&A with migrant justice organizers.",
  },
  {
    id: 20,
    name: "Feminist Strike Assembly",
    slug: "feminist-strike-assembly",
    city: "Edinburgh",
    location: "The Autonomous Centre",
    date: new Date("2025-03-08T11:00:00"),
    organizerName: "Edinburgh Feminist Collective",
    imageUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c",
    description:
      "Planning for the International Women’s Strike. Demands include free childcare, abortion rights, and an end to gendered violence.",
  },
  {
    id: 21,
    name: "Anarcho-Feminist Conference",
    slug: "anarcho-feminist-conference",
    city: "Barcelona",
    location: "Ateneu Rebel",
    date: new Date("2025-05-30T10:00:00"),
    organizerName: "AFC",
    imageUrl: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c",
    description:
      "Reclaiming revolutionary feminist histories and building autonomous care networks. Workshops on self-defense, mutual aid, and queer kinship.",
  },
  {
    id: 22,
    name: "Degrowth Poetry Slam",
    slug: "degrowth-poetry-slam",
    city: "Edinburgh",
    location: "Sandy Bell’s Pub",
    date: new Date("2025-08-14T19:00:00"),
    organizerName: "Edinburgh Radical Arts",
    imageUrl: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad",
    description:
      "Spoken word against capitalism. Themes: anticolonial ecology, class struggle, and queer joy. Pay-what-you-can entry.",
  },
  {
    id: 23,
    name: "Anti-Tourism Direct Action",
    slug: "anti-tourism-direct-action",
    city: "Barcelona",
    location: "Plaza Catalunya",
    date: new Date("2025-10-07T16:00:00"),
    organizerName: "Barri Veïnal Assembly",
    imageUrl: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    description:
      "Reclaiming the city from Airbnb and luxury developers. Guided tour of resistance sites + protest against hotel expansion.",
  },
  {
    id: 24,
    name: "DIY Punk Against Fascism",
    slug: "diy-punk-against-fascism",
    city: "Bristol",
    location: "The Plough",
    date: new Date("2025-11-23T20:00:00"),
    organizerName: "Bristol Antifa Soundsystem",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a5d4",
    description:
      "All-ages gig funding antifascist legal defense. Hardcore, ska, and riot grrrl bands. No Nazis, no TERFs.",
  },
  {
    id: 25,
    name: "Workers’ Cooperative Fair",
    slug: "workers-cooperative-fair",
    city: "Glasgow",
    location: "The Deep End",
    date: new Date("2025-12-05T11:00:00"),
    organizerName: "Glasgow Solidarity Economy",
    imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40",
    description:
      "Meet radical worker-owned businesses—from bakeries to bike repair. Workshops on starting your own co-op.",
  },
  {
    id: 26,
    name: "Trans Healthcare Mutual Aid",
    slug: "trans-healthcare-mutual-aid",
    city: "London",
    location: "DIY Space for London",
    date: new Date("2026-02-14T15:00:00"),
    organizerName: "Trans Liberation Front",
    imageUrl: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622",
    description:
      "Crowdfunding hormone access and safe housing. Skill-share on DIY healthcare and resisting NHS gatekeeping.",
  },
  {
    id: 24,
    name: "Revolutionary Games Night",
    slug: "revolutionary-games-night",
    city: "Barcelona",
    location: "Can Masdeu",
    date: new Date("2026-03-21T18:00:00"),
    organizerName: "Barcelona Anarchist Federation",
    imageUrl: "https://images.unsplash.com/photo-1560253023-3ec5d502959f",
    description:
      "Board games with a twist: ‘Strike Simulator,’ ‘Community Defense Against Cops,’ and ‘Mutual Aid Monopoly.’ Vegan food provided.",
  },
];
